"""Controlled, hypothetical input briefs. Numbers are NOT our measured benchmarks.

Generated drafts must explicitly preserve hypothetical status. Topic partitions
are frozen before generation; no heldout historical post is used as an input.
"""
from common import *
def topic(tid,split,name,typ,facts):
    return {'id':tid,'split':split,'topic':name,'content_type':typ,'audience':'r/LocalLLaMA readers running local language models','style':'clear, restrained, technical English','scenario_status':'Hypothetical experiment brief; not measured results or personal experience. State that status explicitly. Do not invent external facts or benchmarks.','facts':[{'id':f'F{i+1}','text':fact,'status':'synthetic experimental input'} for i,fact in enumerate(facts)]}
TOPICS=[
 topic('D01','tune_dev','A hypothetical VRAM planning checklist','Tutorial / Guide',['The scenario has a 12 GB GPU.','The draft should separate model weights, KV cache, and other runtime allocations.','No actual model or runtime was tested.']),
 topic('D02','tune_dev','A hypothetical time-to-first-token comparison','Experience / Benchmark',['A hypothetical setup A has time-to-first-token of 1.2 seconds and setup B 2.4 seconds.','Both hypothetical runs use the same prompt and hardware.','No throughput, accuracy, or statistical uncertainty measurements were supplied.']),
 topic('S01','selection_dev','Designing a hypothetical RAG sanity check','Tutorial / Guide',['The scenario uses 30 local documents.','Compare retrieval on and retrieval off using the same questions.','Some questions have no answer in the documents.','No actual accuracy results are available.']),
 topic('S02','selection_dev','What would count as evidence that local deployment improves privacy?','Discussion / Opinion',['The scenario keeps prompts on a local machine.','Logs and optional network connections must also be checked.','No security audit or compliance certification was performed.']),
 topic('T01','final_test','A hypothetical quantization comparison with conflicting objectives','Experience / Benchmark',['A hypothetical Q4 configuration uses 6 GB and Q8 uses 10 GB.','On a hypothetical 20-question check, Q4 gets 14 correct and Q8 gets 16 correct.','Hardware and prompts are identical in this scenario.','No real benchmark or significance test was performed.']),
 topic('T02','final_test','A hypothetical context length memory experiment','Experience / Benchmark',['In a hypothetical run, context length 2048 uses 7 GB and 8192 uses 11 GB.','Model, runtime and hardware are held fixed.','No output quality or throughput results were collected.']),
 topic('T03','final_test','Hypothetical local inference speed: what the numbers do not show','Experience / Benchmark',['Two hypothetical runtimes achieve 18 and 24 tokens per second.','The hypothetical test uses one prompt on the same machine.','Time to first token and answer quality were not measured.','The sample does not establish a universal winner.']),
 topic('T04','final_test','A hypothetical batching tradeoff','Experience / Benchmark',['Hypothetical batch size 1 produces 22 tokens per second in total; batch size 4 produces 55 in total.','These are aggregate rates, not per-user rates.','Per-request latency was not measured.','The values are illustrative, not real test results.']),
 topic('T05','final_test','Checklist for a hypothetical offline local model test','Tutorial / Guide',['The scenario allows downloading the model before disconnecting.','The offline check must include generation and checking for network requests.','No actual offline test has been run.']),
 topic('T06','final_test','Designing a hypothetical prompt regression test','Tutorial / Guide',['The scenario has 12 fixed test prompts.','Compare the old and new prompts on the same model settings.','Include answerable and insufficient-information cases.','No improvement results are available yet.']),
 topic('T07','final_test','A hypothetical retrieval failure: what to inspect first','Tutorial / Guide',['The scenario has 40 documents and a query with a known answer in one document.','The relevant document was not among the retrieved passages in the hypothetical failure.','No evidence identifies whether chunking, indexing or query wording caused it.']),
 topic('T08','final_test','Why a hypothetical leaderboard score cannot decide a local deployment','Discussion / Opinion',['In the scenario, a team needs low latency and offline use.','A leaderboard score alone does not measure those requirements.','No particular model is claimed to outperform another.']),
 topic('T09','final_test','A hypothetical comparison: reproducibility before model recommendations','Discussion / Opinion',['The scenario compares two local models.','The model versions, prompt, generation settings and hardware need to be recorded.','No experimental outcome has been provided.']),
 topic('T10','final_test','A precise troubleshooting question for a hypothetical slowdown','Question / Troubleshooting',['The hypothetical setup uses a 16 GB GPU.','The slowdown begins when context length changes from 2048 to 8192.','Model and runtime versions are not yet recorded.','No evidence proves a driver, memory or model issue.'])]
if __name__=='__main__':
    write_json(ROOT/'configs/topic_bank.json',TOPICS)
    write_json(ROOT/'configs/topic_freeze.json',{'at':now(),'sha256':digest(json.dumps(TOPICS,sort_keys=True)),'n_tune':2,'n_selection':2,'n_final':10,'status':'controlled hypothetical facts; no measured or user-authored experience claimed'})
